### ISSUE TITLE
Can I instal tkl-odoo on a existing webmin/virtualmin server?

### ISSUE THREAD

**Issue by topstarnetwork** [CLVsol/tkl-odoo#1]
Can I instal tkl-odoo on a existing webmin/virtualmin server?
Or do I have to instal tkl-odoo on a empty new server fresh instal?
Regards.

**Comment by cvercelino** [comment]
The source code provided in https://github.com/CLVsol/tkl-odoo is a script that will let you create an iso image of an Odoo Appliance, it will not install tkl-odoo on a server. 
You can use the iso image to install tkl-odoo on a new server or new virtual machine.
You need to have some familiarity on creating and installing Turnkey Linux Appliances (http://www.turnkeylinux.org/) to do this.
Please, refer to the documentation provided by this link: https://github.com/turnkeylinux-apps/tkldev/tree/master/docs.
If you need any further help, please leave a note here.
Regards,
Carlos Vercelino

**Comment by topstarnetwork** [comment]
thanks,
my problem is that I already have a webmin/virtualmin hosting several domain websites and I would like to use this server to instal odoo platform instead on insaling odoo platform on a seperate new servr wich will cost me more as I will have to pay again for the new server managment so my question is can I instal the full odoo platform on webmin and alocate the odoo platform to any kind of virtual server instead of using a stand alone odoo server?

**Comment by cvercelino** [comment]
I have never seen an installation of Odoo (https://www.odoo.com/) on a webmin/virtualmin enviroment and for sure '**tkl-oddo**' is not adaptable for that. 
Odoo is a very complex ERP framework (and in version 8.0 a bunch of other apps like Website Builder, e-Commerce, CRM, Point of Sale. etc. where included or reshaped) and usually it will require more than one single dedicated server to be deployed.
The minimal installation of Odoo I have devised up to now you can find here (https://github.com/CLVsol/tklpatch-lamp-odoo-aws) but as the 'tkl-odoo' is not adaptable for a webmin/virtualmin enviroment.

**Comment by cvercelino** [comment]
Oops. I have just close this issue by mistake. I am reopening it again.

I have never seen an installation of Odoo (https://www.odoo.com/) on a webmin/virtualmin enviroment and for sure '**tkl-oddo**' is not adaptable for that. 
Odoo is a very complex ERP framework (and in version 8.0 a bunch of other apps like Website Builder, e-Commerce, CRM, Point of Sale. etc. where included or reshaped) and usually it will require more than one single dedicated server to be deployed.
The minimal installation of Odoo I have devised up to now you can find here (https://github.com/CLVsol/tklpatch-lamp-odoo-aws) but as the 'tkl-odoo' is not adaptable for a webmin/virtualmin enviroment.

**Comment by topstarnetwork** [comment]
Thanks for the info, I guess I have no other choice of installing odoo on a single dedicated server meant for that purpouse,
thank you again for your great support.

**Comment by topstarnetwork** [comment]
Just another littel question, can tkl-odoo
be used as multi tenant (multi domain support)? And host several erp for other ERP domain owners?

**Comment by cvercelino** [comment]
'tkl-odoo' is intended to create an TurnKey Linux Appliance to be used as an dedicated server (fisical or virtual).
To do what you need I think you will have to implement an specific installation of Odoo. To start, maybe you should have a look at this two links:
http://pt.slideshare.net/openobject/launching-your-odoo-saas-offer
http://pragtech.co.in/labs/product-lab/odoo-openerp-saas-kit.html
I have not tried any of then.

**Comment by guru3636** [comment]
topstarnetwork.. even i am trying to find a solution for the same thing which u mentioned above... pls do let me know if you have found out the solution now..
Installing odoo for one domain on a server having virtualmin..and we can replicate the same odoo for other domains and activate it wherever required only.. I am trying to find a solution for this.
